[package]
name = "finite_field"
version = "0.1.0"
authors = ["bababax11 <bababax11@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = "1.12.0"